if [ -z "$PS1" ]; then
   return
fi

if [ -r /etc/bashrc ]; then
    source /etc/bashrc
fi

if [ -r /usr/local/etc/profile.d/bash_completion.sh ]; then
    if [ -d /usr/local/etc/bash_completion.d ]; then
        export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d";
    fi

    source /usr/local/etc/profile.d/bash_completion.sh
fi

if [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
fi

if ls --color=auto &> /dev/null; then
    alias ls="ls --color=auto"
elif gls --color=auto &> /dev/null; then
    alias ls="gls --color=auto"   
else
    export CLICOLOR=1
fi

if [ -r ~/.dircolors ]; then
    if dircolors &> /dev/null; then
        eval $(dircolors -b ~/.dircolors)
    elif gdircolors &> /dev/null; then
        eval $(gdircolors -b ~/.dircolors)
    fi
fi
