if [ -z "$PS1" ]; then
   return
fi

if [ -r /etc/bashrc ]; then
    source /etc/bashrc
fi

if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if [ -f /usr/local/share/bash-completion/bash_completion ]; then
    source /usr/local/share/bash-completion/bash_completion
elif [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
fi

if ls --color=auto &> /dev/null; then
    alias ls="ls --color=auto"
elif gls --color=auto &> /dev/null; then
    alias ls="gls --color=auto"
else
    export CLICOLOR=1
fi

if [ -r ~/.dircolors ]; then
    if dircolors &> /dev/null; then
        eval $(dircolors -b ~/.dircolors)
    elif gdircolors &> /dev/null; then
        eval $(gdircolors -b ~/.dircolors)
    fi
fi
