if [ -z "$PS1" ]; then
   return
fi

if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

if [ -f /usr/local/share/bash-completion/bash_completion ]; then
    source /usr/local/share/bash-completion/bash_completion
fi

if ls --color=auto &> /dev/null; then
    alias ls="ls --color=auto"
elif gls --color=auto &> /dev/null; then
    alias ls="gls --color=auto"   
else
    export CLICOLOR=1
fi

if [ -f ~/.dir_colors ]; then
    if hash dircolors 2>/dev/null; then
        eval `dircolors -b ~/.dir_colors`
    elif hash gdircolors 2>/dev/null; then
        eval `gdircolors -b ~/.dir_colors`
    fi
fi
